### ISSUE TITLE
need more information on exception

### ISSUE THREAD

**Issue by vasco3** [thisiskeith/oq#4]
https://github.com/thisiskeith/oq/blob/master/oq.js#L41
the error feedback from the server is lost at this point.

**Comment by stevus** [comment]
Looks like we should be stringifying this error before we create an error with it. The Error object is doing a toString() on the type, and errorReport is being stored in error.message as '[object Object]'

```
defered.reject(new Error(JSON.stringify(errorReport)));
```

**Comment by thisiskeith** [comment]
lmk if this fixes it:
defered.reject(errorReport);

**Comment by vasco3** [comment]
On the debugger with breakpoint on https://github.com/thisiskeith/oq/blob/master/oq.js#L41
the value of errorRepsonse is:

``` javascript
{
   "statusCode":400,
   "body":"{}",
   "jsonBody":{
      "items":[ ]
   }
}
```

Then I continue to `promise.then(function() {}).fail(function(errorResponse) {});`

and get 

``` javascript
JSON.stringify(errorResponse.message)
""[object Object]""
```

I think the comment from Steven would solve this issue 
[MDN reference.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

``` javascript
new Error([message[, fileName[, lineNumber]]])
```

**Comment by vasco3** [comment]
@thisiskeith  yeah `defered.reject(errorReport);`  should work as well

**Comment by vasco3** [comment]
working well in `v0.2.3`
